apiVersion: batch/v1
kind: Job
metadata:
  name: job-django-createsuperuser
  namespace: edu-victor-shishkalov
spec:
  template:
    spec:
      containers:
        - name: job-createsuperuser
          image: wiwikin/dev-django-site:d66b7d83
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pg-ssl-cert-volume
              mountPath: /certs
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: ALLOWED_HOSTS
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn

            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DJANGO_SUPERUSER_USERNAME
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DJANGO_SUPERUSER_EMAIL
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DJANGO_SUPERUSER_PASSWORD

          command: ["sh", "-c", "./manage.py createsuperuser --noinput"]
      restartPolicy: Never

      volumes:
        - name: pg-ssl-cert-volume
          secret:
            secretName: pg-ssl-cert
            defaultMode: 0644