apiVersion: batch/v1
kind: Job
metadata:
  name: job-django-migrate
spec:
  template:
    spec:
      containers:
      - name: job-migrate
        image: nginx-unit-django-app:1.0
        imagePullPolicy: Never
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: DATABASE_URL
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: DEBUG
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: ALLOWED_HOSTS
        command: ['sh', '-c', './manage.py migrate --noinput']
      restartPolicy: Never